language: python
python:
  - "2.7"
  - "3.6"
install:
  - "pip install pytest-cov coveralls"
  - "pip install -e ."
script: 
  - python -m pytest --cov snuggs --cov-report term-missing
after_success:
  - coveralls
deploy:
  on:
    tags: true
    condition: "$TRAVIS_PYTHON_VERSION = 3.6"
  provider: pypi
  user: mapboxci
  distributions: "sdist bdist_wheel"
