dist: xenial
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
install:
  - "pip install attrs==19.1.0 pytest==4.0.2 hypothesis==4.38.1 pytest-cov coveralls pyparsing~=2.0"
  - "pip install -e .[test]"
script:
  - python -m pytest --cov snuggs --cov-report term-missing
after_success:
  - coveralls
deploy:
  on:
    tags: true
    condition: "$TRAVIS_PYTHON_VERSION = 3.6"
  provider: pypi
  user: __token__
  distributions: "sdist bdist_wheel"
