language: python
python:
  - "2.7"
  - "3.4"
install:
  - "pip install pytest"
  - "pip install coveralls"
  - "pip install -e ."
script: 
  - coverage run --source=snuggs -m py.test
after_success:
  - coveralls
